apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-predictor-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transaction-predictor-app
  template:
    metadata:
      labels:
        app: transaction-predictor-app
    spec:
      containers:
      - name: transaction-predictor-app
        image: shashankjain/transaction-predictor-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-predictor-app
spec:
  selector:
    app: transaction-predictor-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
